// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
          return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKa69HKEvwGbfvi45fYYVzvSIG-rbQZfs',
    appId: '1:54542658770:web:809aa7eb2a17a7fefb510b',
    messagingSenderId: '54542658770',
    projectId: 'ninja-brew-crew-c4bda',
    authDomain: 'ninja-brew-crew-c4bda.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-c4bda.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjBq4EitL_6oIZ3JAGX3Nl8DYNDji67zw',
    appId: '1:54542658770:android:09538bf42ec0a090fb510b',
    messagingSenderId: '54542658770',
    projectId: 'ninja-brew-crew-c4bda',
    storageBucket: 'ninja-brew-crew-c4bda.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8yfqtn7Cm3UGnw4UQWv8GGOUPEBJ7CkE',
    appId: '1:54542658770:ios:a2d386ad60259bd6fb510b',
    messagingSenderId: '54542658770',
    projectId: 'ninja-brew-crew-c4bda',
    storageBucket: 'ninja-brew-crew-c4bda.appspot.com',
    iosClientId: '54542658770-qc91qreihgcce1liua5uqnd3v665l93f.apps.googleusercontent.com',
    iosBundleId: 'com.thenetninja.brewcrew.brewCrew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8yfqtn7Cm3UGnw4UQWv8GGOUPEBJ7CkE',
    appId: '1:54542658770:ios:a2d386ad60259bd6fb510b',
    messagingSenderId: '54542658770',
    projectId: 'ninja-brew-crew-c4bda',
    storageBucket: 'ninja-brew-crew-c4bda.appspot.com',
    iosClientId: '54542658770-qc91qreihgcce1liua5uqnd3v665l93f.apps.googleusercontent.com',
    iosBundleId: 'com.thenetninja.brewcrew.brewCrew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKa69HKEvwGbfvi45fYYVzvSIG-rbQZfs',
    appId: '1:54542658770:web:809aa7eb2a17a7fefb510b',
    messagingSenderId: '54542658770',
    projectId: 'ninja-brew-crew-c4bda',
    authDomain: 'ninja-brew-crew-c4bda.firebaseapp.com',
    storageBucket: 'ninja-brew-crew-c4bda.appspot.com',
  );
}
